name: Build Executable

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim-bookworm     
         
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Build executable
      run: pyinstaller --onefile --paths rxmockup --name executable main.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable-${{ github.sha }}
        path: dist/executable
        retention-days: 30